---
apiVersion: v1
kind: Service
metadata:
  name: ad
spec:
  selector:
    app: ad # Pod 이름
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  labels:
    app: ad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad # Pod 이름
  template:
    metadata:
      labels:
        app: ad
    spec:
      containers:
        - name: ad
          image: lmslmsms0616/chatbot-advertisement:{jenkins build number}
          ports:
            - containerPort: 8080 # 컨테이너 포트
