---
apiVersion: v1
kind: Service
metadata:
  name: del
spec:
  selector:
    app: del # Pod 이름
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: del
  labels:
    app: del
spec:
  replicas: 1
  selector:
    matchLabels:
      app: del # Pod 이름
  template:
    metadata:
      labels:
        app: del
    spec:
      containers:
        - name: del
          image: lmslmsms0616/chatbot-delivery:{jenkins build number}
          ports:
            - containerPort: 8080 # 컨테이너 포트
