---
apiVersion: v1
kind: Service
metadata:
  name: cicd_demo
spec:
  selector:
    app: cicd_demo # Pod 이름
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd_demo
  labels:
    app: cicd_demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd_demo # Pod 이름
  template:
    metadata:
      labels:
        app: cicd_demo
    spec:
      containers:
        - name: cicd_demo
          image: lmslmsms0616/sa-project # docker image
          ports:
            - containerPort: 8080 # 컨테이너 포트
